version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://techcar-api:3333
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://techcar-api:3333
    restart: unless-stopped